[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm",
  "pnpm install --frozen-lockfile=false"
]

[phases.build]
cmds = [
  "PORT=3000 BASE_PATH=/ pnpm --filter @workspace/boutique run build",
  "pnpm --filter @workspace/api-server run build"
]

[start]
cmd = "pnpm --filter @workspace/api-server run start"
